version: '3.8'

services:
  backend:
    image: walnut-backend:latest  # Custom image name and tag
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: walnut-frontend:latest  # Custom image name and tag
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
